#!/bin/sh
exec scala "$0" "$@"
!#

import util.control.Breaks._

def CliFormatter() = {
      //val input = scala.io.StdIn.readLine()
      for (input <- scala.io.Source.stdin.getLines) {

        if (input.startsWith("{"))
          input.drop(1).split("\\b(\\w*CN\\w*)\\b").filter(! _.isEmpty).map(s => "CN" + s).foreach(x => println(Console.BLUE + x + "\n"))
        else println(Console.WHITE + input)
      }
      break()
    }

CliFormatter()


## cat log.txt | sh scala.sh

### java -cp MyJar.jar com.mycomp.myproj.AnotherClassWithMainMethod